services:
  api:
    build: .
    ports:
      - '3000:3000'
    environment:
      - NODE_ENV=development
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USERNAME=postgres
      - DB_PASSWORD=postgres
      - DB_DATABASE=brain_agriculture
    depends_on:
      - db
    volumes:
      - ./:/app
      - /app/node_modules
    command: npm run start:dev

  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_DB: brain_agriculture
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
